name: pdf_viewer_plugin
description: A Flutter plugin for IOS and Android providing a simple way to display local file PDFs (enter to see some gifs).
version: 2.0.1
homepage: https://github.com/lubritto/pdf_viewer_plugin

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=2.10.1"

dependencies:
  flutter:
    sdk: flutter
  pedantic: ^1.11.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: dev.britto.pdf_viewer_plugin
        pluginClass: PdfViewerPlugin
      ios:
        pluginClass: PdfViewerPlugin
